### ISSUE TITLE
Have !checkPermissions take a channel as an argument

### ISSUE THREAD

**Issue by alopezlago** [alopezlago/QuizBowlDiscordScoreTracker#25]
!checkPermissions only checks the current channel's permissions, to see if the bot can run on it. We should see if having it take a channel as an optional argument would be beneficial, since this command could then be run in a hidden channel.

**Comment by Sam-per** [comment]
Hi! I'd like to work on this issue. Could I be assigned to it please? Thank you

**Comment by alopezlago** [comment]
Sure, I've assigned it to you.
