### ISSUE TITLE
Add !reloadTeamRoles to pick up new roles with the team role prefix

### ISSUE THREAD

**Issue by alopezlago** [alopezlago/QuizBowlDiscordScoreTracker#43]
Add a `!reloadTeamRoles` command to load new roles that have the team role prefix. This way, we don't have to restart the game if some teams were missing.

**Comment by mk625sn** [comment]
Hello, I would like to try to working on it. Could you assign it to me please? thank you

**Comment by mk625sn** [comment]
Hello, I would like to try to working on this issue. Could you assign it to me please? Thank you

**Comment by alopezlago** [comment]
Sure! Here are some of the design constraints:
- Team names should be case-insensitive, so "ALPHA" and "alpha" are the same team.
- If the team name must include a comma in it, it should be escaped by doubling the character. For example, the team "One, Two, Three" should be written as "One,, Two,, Three" so that we don't create three teams "One", "Two", and "Three".
- We should only allow up to GeneralCommandHandler.MaxTeamsShown teams
- If the team role prefix is set in the server, ignore the teams. We use the ByRoleTeamManager whenever the team role prefix is set.


TeamNameParser.cs should have most of the logic for parsing the team names (like escaping commas). It needs to be modified to be case-insensitive, and to accept a parameter that limits the number of teams. Case-insensitivity can be done by passing in the right StringComparer class to the previousTeamName's HashSet constructor.

I suggest making TeamNameParser (and the tests) work with those constraints, then updating GeneralCommandHandler.SetNewReader to accept a string of combined team names. In that method, use TeamNameParser to get the team names, and add them to the ByCommandTeamManager.

If you have any further questions, feel free to ask.

**Comment by alopezlago** [comment]
Fixed by #69
