### ISSUE TITLE
Auto-mute after buzz

### ISSUE THREAD

**Issue by SilverStats** [alopezlago/QuizBowlDiscordScoreTracker#6]
For a voice packet, the bot could auto-mute the reader (or all parties) for a short amount of time, to prevent hearing more after a buzz occurs. I don't know what the right amount of time is exactly but it should be easy to get to something reasonable--maybe 500 milliseconds?

**Comment by alopezlago** [comment]
That's a good idea. I'll need to add a voice channel pairing to the config, and then look up the voice channel API for Discord.Net. I'll try to work on it when I find some time.

**Comment by alopezlago** [comment]
It looks like DSharpPlus has some issues with removing permission overwrites, where it treats 'Deny' overwrites as 'Allow' ones. I may need to rewrite this in Discord.Net to get this.

**Comment by alopezlago** [comment]
Fixed by #7
