### ISSUE TITLE
!end should not clear the score from the last time

### ISSUE THREAD

**Issue by mbentley00** [alopezlago/QuizBowlDiscordScoreTracker#92]
There have been multiple instances when using the bot for Festivus that people typed "!end" to end the game without first revealing the score. As far as I can tell, this either gets rid of the score or at least makes it harder to get. I'd suggest not letting an "!end" happen until the score has first been shown, or to by default show the score before ending.

**Comment by alopezlago** [comment]
Similar to #81, but makes sense. Showing the result of !gameReport instead might make more sense, but !score is reasonable too.
